# Generated by Django 3.1 on 2020-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MODBUS', 'MODBUS'), ('SERIAL', 'SERIAL')], max_length=100)),
                ('port_name', models.CharField(help_text='ex : /dev/ttyUSB0', max_length=100)),
                ('baudrate', models.IntegerField(default=9600)),
                ('timeOut', models.IntegerField(default=1, help_text='<1')),
            ],
        ),
    ]
